# Spring properties
spring:
  application:
     name: todo-list

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port